name: pc_parts_store
description: Flutter E-Commerce app for PC components - Offline First
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^13.2.0

  # UI
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  badges: ^3.1.2

  # Local DB
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0

  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.3
  google_fonts: ^8.2.0
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
